# fly.toml app configuration file generated for johnandmaritza on 2026-02-17T12:16:12-08:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'kith'
primary_region = 'dfw'
swap_size_mb = 2048

[build]
image = 'kith:latest'

[http_service]
auto_start_machines = false
auto_stop_machines = 'off'
internal_port = 5232
min_machines_running = 1

[env]
KITH_ADDRESSBOOK = "personal"
KITH_AUTH_PASSWORD_HASH = "$argon2id$v=19$m=19456,t=2,p=1$tdUU2bctCehhlxe6Mfwv5g$muup0JLA8lJyl7UVfqvKsnGKG+zOU59W/kyLIlbWBak"
KITH_AUTH_USERNAME = "johnbchron"
KITH_BASE_URL = "https://contacts.jlewis.sh"
KITH_HOST = "[::]"
KITH_PORT = "5232"
KITH_STORE_PATH = "/data/contacts.db"

[mounts]
destination = "/data"
initial_size = "1gb"
source = "kith_data"

[[vm]]
size = 'shared-cpu-1x'
