# fly.toml app configuration file generated for kith on 2026-02-22T23:51:12-08:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'kith'
primary_region = 'dfw'
swap_size_mb = 2048

[build]
  image = 'kith:latest'

[http_service]
  internal_port = 5232
  auto_stop_machines = 'off'
  auto_start_machines = false
  min_machines_running = 0

[[vm]]
  size = 'shared-cpu-1x'
